### ISSUE TITLE
Sorry but what is this for? It seems it is something new that I am unaware of.

### ISSUE THREAD

**Issue by Zezo12345** [Lambda11/fishy-AFKer#1]
Does afk - active-bot - fishing send to the server that you are afk while you do that?

**Comment by Zezo12345** [comment]
or is it same as "afker" mod that prevents you to go to server select screen?

**Comment by Owyn** [comment]
> Does afk - active-bot - fishing send to the server that you are afk while you do that?

Yes it does.

After 5 minutes of no input from the user - client sends your afk status to the server

**Comment by Zezo12345** [comment]
I didnt know that auto-fishing mod does this, has there been reports of people being banned due to this?

**Comment by Owyn** [comment]
It's the game itself which does this, people might start getting banned any day, would probably be a one big banwave instead of individual bannings

**Comment by Zezo12345** [comment]
Thank you for this mod, although it says afk status true when it returns false, might be abit confusing :)

**Comment by Zezo12345** [comment]
Op-code for EU is 52850 :)
